### ISSUE TITLE
404 when editing a store

### ISSUE THREAD

**Issue by GuillaumeAmat** [Mapotempo/mapotempo-web#3]
1. Go to the store edition page
2. In the Street field, type : avenue Victor Hugo

Result:
![capture d ecran de 2015-07-06 11-06-39](https://cloud.githubusercontent.com/assets/1179174/8518987/54839fa4-23cf-11e5-98ef-ed2156f15a96.png)

**Comment by frodrigo** [comment]
It's due to unconfigured IGN API key. Returns on error from IGN server, and throwing it through json request.
