### ISSUE TITLE
Automatic insertion doesn't work

### ISSUE THREAD

**Issue by GuillaumeAmat** [Mapotempo/mapotempo-web#6]
On the planning page, when clicking on the light bulb to insert automaticaly a destination, Mapotempo displays an error:
![capture d ecran de 2015-07-06 14-13-45](https://cloud.githubusercontent.com/assets/1179174/8521959/7e5a5952-23e9-11e5-98be-82ab1529dc07.png)

**Comment by frodrigo** [comment]
RGeo is a localy build gem and available features depends on package installed on system before build. Need install libgeos-dev and/or libgeos++-dev and reinstall rgeo.

**Comment by GuillaumeAmat** [comment]
Ok thanks
